### ISSUE TITLE
Realizar Strike en tirada pasada

### ISSUE THREAD

**Issue by TechHoruser** [jemaji/bowling-app#3]
Se ha detectado que si se vuelve a realizar un strike en una tirada previa a la última, la cual no tuviese antes dicho strike, no se reinicia la puntuación de su segunda tirada y muestra un score inválido. 

Solución: Si se efectúa strike en una ronda, establecer siempre la puntuación de su segunda tirada a Set vacío.

**Comment by jmateos-xt** [comment]
fix in commit 31f29a92f6b053307b506f19b6eac708edd043c1
