### ISSUE TITLE
Round list as disabled

### ISSUE THREAD

**Issue by TechHoruser** [jemaji/bowling-app#5]
He pasado de rondas con normalidad y se han quedado como deshabilitadas 🤷‍♂️

Observar también que no se actualizan las bolas de abajo de las tiradas.

Creo que se debe a que cuando se lanza la tirada 2 si la 1 es null establecer a empty Set 

Caso de uso debajo de la imagen.

![image](https://user-images.githubusercontent.com/14580756/167700547-3d7044bb-a6b4-4309-952d-02c52c0f5202.png)

Caso de uso:
1. Refreso (CocaCola Cero) y F5 🤣
2. Selecciono bola de la segunda tirada.
3. Click en spare

**Comment by jmateos-xt** [comment]
fix issue in b8e2943c156e73e43d50acf69b3084db92ba5875
